### ISSUE TITLE
CppyyLegacy::TMetaUtils::GetNameTypeForIO, missing type

### ISSUE THREAD

**Issue by hexomethyl** [wlav/cppyy-backend#29]
As per #28, I have encountered another issue relating to typedefs (I suspect). 

Cppyy fails to find a type for IO using its name. I suspect that this is due to the type being utilized via a typedef 
`using HypothesisTrees = std::pmr::vector<std::pmr::vector<std::unique_ptr<Bernoulli>>>;` 

The typedef is then used within the class to define a field 

`HypothesisTrees trees;`

Cppyy attempts to generate the code for the class and fails in `[libCling.so] CppyyLegacy::TMetaUtils::GetNameTypeForIO[abi:cxx11](const clang::QualType &, const cling::Interpreter &, const CppyyLegacy::TMetaUtils::TNormalizedCtxt &, CppyyLegacy::TClassEdit::EModType) TClingUtils.cxx:3826`

Do you have any ideas as to what is causing this ?, or as to how I can help investigate it further ?

Below I have attached screenshots of the call stack and function contexts.

![image](https://github.com/user-attachments/assets/d6fcaa4b-b02c-45b0-b539-6aa88de76ab2)

`[libCling.so] CppyyLegacy::TMetaUtils::WriteClassCode TClingUtils.cxx:2508`
![image](https://github.com/user-attachments/assets/0a563943-8557-4b80-a0b6-14015254e0c4)

`[libCling.so] CppyyLegacy::TMetaUtils::WritePointersSTL TClingUtils.cxx:2181`
![image](https://github.com/user-attachments/assets/4ccf12cf-3572-4a8d-b5cd-561cb9351045)

`[libCling.so] CppyyLegacy::Internal::RStl::GenerateTClassFor RStl.cxx:65`
![image](https://github.com/user-attachments/assets/15d80fa6-235b-4277-8e7e-5a14b3b1f86a)

`[libCling.so] CppyyLegacy::TMetaUtils::GetTypeForIO TClingUtils.cxx:3847`
OMITTED (Thin wrapper)

`[libCling.so] CppyyLegacy::TMetaUtils::GetNameTypeForIO[abi:cxx11](const clang::QualType &, const cling::Interpreter &, const CppyyLegacy::TMetaUtils::TNormalizedCtxt &, CppyyLegacy::TClassEdit::EModType) TClingUtils.cxx:3826`
![image](https://github.com/user-attachments/assets/0e5d7712-e8fc-4337-9d9c-adc4ab2e6fb5)
![image](https://github.com/user-attachments/assets/79752c18-2cea-4769-81f5-e766baa2556a)
`thisTypeName: std::vector<std::vector<std::unique_ptr<tracking::filter::Bernoulli>,std::pmr::polymorphic_allocator<std::unique_ptr<tracking::filter::Bernoulli>>>,std::pmr::polymorphic_allocator<std::vector<std::unique_ptr<tracking::filter::Bernoulli>,std::pmr::polymorphic_allocator<std::unique_ptr<tracking::filter::Bernoulli>>>>>`

`thisTypeNameForIO: std::vector<std::vector<tracking::filter::Bernoulli*,std::pmr::polymorphic_allocator<std::unique_ptr<tracking::filter::Bernoulli>>>,std::pmr::polymorphic_allocator<std::vector<std::unique_ptr<tracking::filter::Bernoulli>,std::pmr::polymorphic_allocator<std::unique_ptr<tracking::filter::Bernoulli>>>>>`

**Comment by wlav** [comment]
I see `rootcling` in the stack trace, so I assume this is coming from building a dictionary? Can you add the `--interpreteronly` flag (I've already added this for the 3.5.0 release) to disable I/O streamers in the dictionary?

I left I/O in way back when, thinking I'd make it into a feature at one point, but I never found the time, so it doesn't really work (beyond the most basic cases anyway).

**Comment by hexomethyl** [comment]
> I see `rootcling` in the stack trace, so I assume this is coming from building a dictionary? Can you add the `--interpreteronly` flag (I've already added this for the 3.5.0 release) to disable I/O streamers in the dictionary?
> 
> I left I/O in way back when, thinking I'd make it into a feature at one point, but I never found the time, so it doesn't really work (beyond the most basic cases anyway).

That worked :)
